apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wireguard
spec:
  releaseName: wg-easy
  chart:
    spec:
      chart: wg-easy
      sourceRef:
        kind: HelmRepository
        name: wg-easy
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: weejewel/wg-easy
      tag: 7
    wireguard:
      service:
        port: 50000
      dns: 192.168.0.120
    persistence:
      enabled: true
      storageClass: longhorn    
  valuesFrom:
    - kind: Secret
      name: wg-easy-secrets
      valuesKey: wg-easy-secrets.yaml
      optional: false  