apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: netdata
spec:
  releaseName: netdata
  chart:
    spec:
      chart: netdata
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: netdata/netdata
      tag: v1.37.1
    sd:
      image:
        repository: netdata/agent-sd
        tag: v0.2.7
    parent:
      database:
        persistence: true
        storageclass: "longhorn"
        volumesize: 2Gi
      alarms:
        persistence: true  
        storageclass: "longhorn"
        volumesize: 1Gi
      configs:
        netdata:
          enabled: true
          path: /etc/netdata/netdata.conf
          data: |
            [global]
              memory mode = dbengine
              update every = 3
            [ml]
              enabled = no
            [plugins]
              cgroups = no
              tc = no
              enable running new plugins = no
              check for new plugins every = 72000
              python.d = no
              charts.d = no
              go.d = no
              node.d = no
              apps = no
              proc = no
              idlejitter = no
              diskspace = no      
        temperature:
          enabled: true
          path: /etc/netdata/health.d/temperature.conf
          data: |
            alarm: temperature_alarm
               on: sensors.cpu_thermal-virtual-0_temperature
            lookup: average -3s   
            units: celsius
            every: 5s
            warn: $this > 60
            crit: $this > 70
            info: cpu temperature
              to: sysadmin  
      env: 
        DO_NOT_TRACK: 1
    child:
      env: 
        DO_NOT_TRACK: 1
    k8sState:
      persistence:
        enabled: true
        storageclass: "longhorn"
        volumesize: 1Gi
      env: 
        DO_NOT_TRACK: 1
  valuesFrom:
    - kind: Secret
      name: netdata-secrets
      valuesKey: netdata-secrets.yaml
      optional: false  
