apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: databases
spec:
  releaseName: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator-crds
      version: "25.10.2"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3