apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: databases
spec:
  releaseName: mariadb-operator
  chart:
    spec:
      chart: mariadb-operator
      version: "25.10.2"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    currentNamespaceOnly: true
    webhook:
      cert:
        certManager:
          enabled: true