apiVersion: v1
kind: Secret
metadata:
  name: mariadb-operator
  namespace: databases
type: Opaque
data:
  mariadb-root-password: ${MARIADB_ROOT_PASSWORD}
  nextcloud-password: ${NEXTCLOUD_DATABASE_PASSWORD}
  ha-password: ${HA_DATABASE_PASSWORD}