apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  releaseName: mariadb
  chart:
    spec:
      chart: mariadb
      version: "18.0.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    auth:
      rootPassword: ${MARIADB_ROOT_PASSWORD}
    architecture: standalone
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 10Gi