apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.29.2.6364-6d72b0cf6
      pullPolicy: IfNotPresent
    env:
      TZ: Asia/Kolkata 
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        accessMode: ReadWriteOnce
      data:
        enabled: true
        type: nfs
        server: 192.168.0.120
        path: /data/media/Movies
        accessMode: ReadWriteOnce
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568   
  valuesFrom:
    - kind: Secret
      name: plex-secrets
      valuesKey: plex-secrets.yaml
      optional: true