apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 5m
  timeout: 20m
  install:
    remediation:
      retries: 3
